spring:
  application:
    name: OAuth2
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oauth2-project
    username: postgres
    password: Pheaktra@8899
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true

logging:
  level:
    org.springframework.security: trace
